# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0fResponseMessage\x12\r\n\x05reply\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTMESSAGE._serialized_start=17
  _REQUESTMESSAGE._serialized_end=50
  _RESPONSEMESSAGE._serialized_start=52
  _RESPONSEMESSAGE._serialized_end=84
# @@protoc_insertion_point(module_scope)
